ionos: &ionos
  AWS_ACCESS_KEY_ID: "ionos_asc"
  AWS_SECRET_ACCESS_KEY: "ionos_sc"

hetzner: &hetzner
  AWS_ACCESS_KEY_ID: "hetzner_asc"
  AWS_SECRET_ACCESS_KEY: "hetzner_sc"

vaultwarden: &vaultwarden
  app: vaultwarden
  pre_backup: ascsa
  post_backup: asd
  include:
    - /abc
    - /def
  exclude:
    - /ghi
  hc_slug: vaultwarden-backup

opengist: &opengist
  app: opengist
  pre_backup: ascsa
  post_backup: asd
  include:
    - /abc
    - /def
  exclude:
    - /ghi
  hc_slug: opengist-backup

backup:
  - <<: *vaultwarden
    <<: *ionos
    RESTIC_REPOSITORY: "repo_vw_ionos"
    RESTIC_PASSWORD: "password"

  - <<: *vaultwarden
    <<: *hetzner
    RESTIC_REPOSITORY: "repo_vw_hetzner"
    RESTIC_PASSWORD: "password1"

  - <<: *opengist
    <<: *ionos
    RESTIC_REPOSITORY: "repo_og_ionos"
    RESTIC_PASSWORD: "password"

  - <<: *opengist
    <<: *hetzner
    RESTIC_REPOSITORY: "repo_og_hetzner"
    RESTIC_PASSWORD: "password1"