[hc]
ping_key = ""

[restic]
docker_image = "restic/restic:0.18.0"

[vaultwarden]
hc_slug = "vaultwarden-backup"
data_volume = "vaultwarden-data"

[opengist]
hc_slug = "opengist-backup"
data_volume = "opengist-data"