services:
  caddy:
    container_name: caddy
    build:
      context: ./conf.d/caddy
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/data
      - ./config:/config
      - ../conf.d/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - garage
