services:
  vaultwarden:
    image: vaultwarden/server:1.34.1
    container_name: vaultwarden
    restart: unless-stopped
    read_only: true
    environment:
      TZ: Europe/Berlin

      DOMAIN: "https://vaultwarden.${DOMAIN}"
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}

      SIGNUPS_ALLOWED: false
      INVITATIONS_ALLOWED: false

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_USERNAME: ${VAULTWARDEN_SMTP_USERNAME}
      SMTP_PASSWORD: ${VAULTWARDEN_SMTP_PASSWORD}
      SMTP_FROM: ${VAULTWARDEN_SMTP_FROM}

    volumes:
      - ./vaultwarden/data:/data/

    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.${DOMAIN}`)
      - traefik.http.routers.vaultwarden.entrypoints=https
      - traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80

  backup:
    image: ghcr.io/optimistic-cloud/toolkit
    container_name: backup-toolkit
    restart: unless-stopped
    hostname: ${WORKLOAD}-backup-toolkit
    user: "1000:1000"
    depends_on:
      - vaultwarden
      - opengist
      - gitea
      - pocket-id
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./crontab:/etc/crontab

      - ./vaultwarden/:/opt/vaultwarden/:ro
      - ./opengist/:/opt/opengist/:ro
      - ./gitea/:/opt/gitea/:ro
      - ./pocket-id/:/opt/pocket-id/:ro


