services:
  restic:
    image: restic/restic:0.18.1
    hostname: ${HOSTNAME:-vaultwarden-backup}
    # profiles:
    #   - restic
    restart: "no"
    stdin_open: true
    user: "0:0" # TODO
    environment:
      TZ: Europe/Berlin
      RESTIC_CACHE_DIR: /root/.cache/restic
    env_file:
      - ${RESTIC_ENV_FILE:?RESTIC_ENV_FILE is required}
    volumes:
      - restic-cache:/root/.cache/restic
      - /mnt/data/m700/vaultwarden:/repo
      - vaultwarden-data:/data/vaultwarden-data:ro
      - ./export-data:/data/export
      - ./restore-data:/data/restore-data

volumes:
  restic-cache:
    name: restic-cache
  vaultwarden-data:
    name: vaultwarden-data
    external: true