services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest@sha256:034bb79c668dbd861e8d1ea131ad9c7abfe136e423edf80efaf502f8aae9c127
    command: agent
    restart: unless-stopped
    ports:
      - "7007:7007"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  beszel-agent:
    image: henrygd/beszel-agent:latest@sha256:bd0caeb8fe3c52f5099d931467adc84f7427f333b8122337e4e1a861e7b1490a
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - beszel-agent-data:/var/lib/beszel-agent
      - beszel-socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://beszel.optimistic.cloud
      TOKEN: ${BESZEL_TOKEN}
      KEY: ${BESZEL_KEY}

volumes:
  beszel-socket:
    name: beszel-socket
  beszel-agent-data:
    name: beszel-agent-data