services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest@sha256:2f8d5c2b6181533a58246313b1d840a69ae04e6c1010e2f6bb52c2228342b443
    command: agent
    restart: unless-stopped
    ports:
      - "7007:7007"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  beszel-agent:
    image: henrygd/beszel-agent:latest@sha256:8874e2c53f9de5e063a6a80d6b617e20fa593ac5dc4eb4c6ce1f912f510f38f8
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - beszel-agent-data:/var/lib/beszel-agent
      - beszel-socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://beszel.optimistic.cloud
      TOKEN: ${BESZEL_TOKEN}
      KEY: ${BESZEL_KEY}

volumes:
  beszel-socket:
    name: beszel-socket
  beszel-agent-data:
    name: beszel-agent-data