services:
  vaultwarden-restore:
    image: vaultwarden/server:1.34.3
    container_name: vaultwarden-restore
    restart: unless-stopped
    read_only: true
    ports:
      - '127.0.0.1:8200:80'
    volumes:
      - ./restore/backup/data:/data/
