networks:
  m700_default:
    external: true

services:
  vaultwarden-restore:
    image: vaultwarden/server:1.34.3
    container_name: vaultwarden-restore
    restart: unless-stopped
    read_only: true
    environment:
      - DOMAIN: https://vaultwarden-restore.optimistic.cloud
    ports:
      - '8200:80'
    volumes:
      - ./restore/backup/data:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden-restore.rule=Host(`vaultwarden-restore.${DOMAIN}`)"
      - "traefik.http.routers.vaultwarden-restore.entrypoints=https"
      - "traefik.http.routers.vaultwarden-restore.tls.certresolver=letsencrypt"
      - "traefik.http.services.vaultwarden-restore.loadbalancer.server.port=80"
    networks:
      - m700_default