services:
  vaultwarden-restore:
    image: vaultwarden/server:1.34.3
    container_name: vaultwarden-restore
    restart: unless-stopped
    read_only: true
    environment:
      TZ: Europe/Berlin
      DOMAIN: https://vaultwarden-restore.optimistic.cloud
    volumes:
      - ./restore/backup/data:/data/
    ports:
      - "8200:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/alive"]
      interval: 180s
      timeout: 10s
      retries: 5
      start_period: 60s
