set shell := ["bash", "-eoux", "pipefail", "-c"]

set dotenv-load

help:
  just --list --list-submodules

####################################
######## DOCKER             ########
####################################

[group('docker')]
[doc('Start the stack')]
up:
  docker compose up -d --remove-orphans

[group('docker')]
[doc('Stop the stack')]
down:
  docker compose down --remove-orphans

[group('docker')]
[doc('Restart application stack')]
restart: down && up

[group('docker')]
[doc('Get logs for the application')]
logs:
  docker compose logs -f

[group("docker")]
[doc('List data of the application')]
ls-gitea-data:
  just ls-volume-data gitea-data

[group("docker")]
[doc('List docker volume data')]
[private]
ls-volume-data export_path:
  docker run --rm -v {{export_path}}:/data:ro alpine ls -la /data

####################################
######## BACKUP             ########
####################################

[group("backup")]
backup +backup_targets:
  #!/usr/bin/env bash
  set -euo pipefail

  run_id=$(cat /proc/sys/kernel/random/uuid)

  export_path=${EXPORT_DATA}

  cleanup() {
    echo "Cleaning up..."
    status=$?
    just up || true
    just _cleanup || true
    exit "$status"
  }
  
  trap cleanup EXIT

  do_backup() {
    for backup_target in {{backup_targets}}; do
      curl -fsS -m 10 --retry 5 -o /dev/null "https://${HC_API}/ping/${HC_PING_KEY}/gitea-${backup_target}/start?create=1&rid=${run_id}"

      on_error() {
        curl -fsS -m 10 --retry 5 -o /dev/null "https://${HC_API}/ping/${HC_PING_KEY}/gitea-${backup_target}/fail?rid=${run_id}"
      }
      trap on_error ERR

      log=$(just restic-backup "$backup_target")
      exit_code=$?
      curl -fsS -m 10 --retry 5 -o /dev/null --data-raw "${log}" "https://${HC_API}/ping/${HC_PING_KEY}/gitea-${backup_target}/${exit_code}?rid=${run_id}"

      log=$(just restic-check "$backup_target")
      exit_code=$?
      curl -fsS -m 10 --retry 5 -o /dev/null --data-raw "${log}" "https://${HC_API}/ping/${HC_PING_KEY}/gitea-${backup_target}/${exit_code}?rid=${run_id}"

      log=$(just restic-forget "$backup_target")
      exit_code=$?
      curl -fsS -m 10 --retry 5 -o /dev/null --data-raw "${log}" "https://${HC_API}/ping/${HC_PING_KEY}/gitea-${backup_target}/${exit_code}?rid=${run_id}"
    done
  }

  mkdir -p "$export_path"
  bash prepare_backup_data.sh "$export_path"
  do_backup

[group("backup")]
[private]
export-env container_name export_path:
  docker container inspect {{container_name}} | jq -r '.[0].Config.Env[]' > "{{export_path}}/{{container_name}}.env"

[group("backup")]
restore backup_target snapshot_id="latest":
  #!/usr/bin/env bash
  mkdir -p "${RESTORE_DATA}"
  just restic-restore {{backup_target}} {{snapshot_id}}

####################################
######## RESTIC             ########
####################################

[group('restic')]
[doc('Init repository')]
restic-init backup_target:
  just _restic-run {{backup_target}} init

[group('restic')]
[doc('Backup data')]
[private]
restic-backup backup_target:
  #!/usr/bin/env bash

  git_commit=$(git ls-remote https://github.com/optimistic-cloud/home-ops.git HEAD | cut -f1)
  just _restic-run {{backup_target}} --tag "git_commit=${git_commit}" --exclude-caches --skip-if-unchanged --json --quiet backup /data | jq

[group('restic')]
[doc('Restore data')]
[private]
restic-restore backup_target snapshot_id:
  just _restic-run {{backup_target}} restore {{snapshot_id}} --target /restore-data

[group('restic')]
[doc('Get snapshots')]
restic-snapshots backup_target count="5":
  just _restic-run {{backup_target}} --quiet snapshots --latest {{count}}

[group('restic')]
[doc('List files in the latest snapshot')]
restic-ls backup_target snapshot_id="latest":
  just _restic-run {{backup_target}} --quiet ls {{snapshot_id}}

[group('restic')]
[doc('Get stats of the repository')]
restic-stats backup_target:
  just _restic-run {{backup_target}} stats --mode raw-data

[group('restic')]
[doc('Unlock repository')]
restic-unlock backup_target:
  just _restic-run {{backup_target}} --quiet unlock

[group('restic')]
[doc('Forget old snapshots')]
restic-forget backup_target keep-within="365d":
  just _restic-run {{backup_target}} --quiet forget --keep-within {{keep-within}}

[group('restic')]
[doc('Prune snapshots')]
restic-prune backup_target:
  just _restic-run {{backup_target}} --quiet prune

[group('restic')]
[doc('Check snapshots')]
restic-check backup_target read-data-subset="33%":
  just _restic-run {{backup_target}} --json check --read-data-subset {{read-data-subset}} | jq

[group('restic')]
[private]
[doc('For each restic command but not backup, as it needs additional volumes and environment variables')]
_restic-run backup_target +restic_args:
  #!/usr/bin/env nu

  let backup_target = "{{backup_target}}"

  with-env { 
    HOSTNAME: "m700"
    RESTIC_ENV_FILE: $"($backup_target).restic.env" 
  } {
    ^docker compose -f docker-compose.backup.yaml run --rm restic {{restic_args}}
  }

[group('utils')]
[private]
[doc('Removes temporary files created during backup')]
_cleanup:
  docker run --rm -v "${EXPORT_DATA}":/data:ro alpine ls -la /data/*
  docker run --rm -v "${EXPORT_DATA}":/data alpine rm -rf /data/*
  docker run --rm -v "${RESTORE_DATA}":/data alpine rm -rf /data/*
  rm -rf "${EXPORT_DATA}"
  rm -rf "${RESTORE_DATA}"