name: wallos

services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:4.8.4@sha256:e4ca23a5b56d3f3e36987db9e38faa2b88adb0df0453852346689e6397daac83
    expose:
      - "80"
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - wallos-data:/var/www/html
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 180s
      timeout: 30s
      retries: 5
      start_period: 60s
    networks:
      - m700_default

volumes:
  wallos-data:
    name: wallos-data
    external: true

networks:
  m700_default:
    external: true