name: wallos

services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:4.8.2@sha256:3a0dd22338ab5edcaddbc12af711807fd57e0457aecbe7b6ec5f72a142718149
    expose:
      - "80"
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - wallos-data:/var/www/html
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 180s
      timeout: 30s
      retries: 5
      start_period: 60s
    networks:
      - m700_default

volumes:
  wallos-data:
    name: wallos-data
    external: true

networks:
  m700_default:
    external: true