services:
  restic:
    image: restic/restic:0.18.1
    hostname: ${HOSTNAME:?HOSTNAME is required}
    # profiles:
    #   - restic
    restart: "no"
    stdin_open: true
    user: "0:0" # TODO
    environment:
      TZ: Europe/Berlin
      RESTIC_CACHE_DIR: /root/.cache/restic
    env_file:
      - ${RESTIC_ENV_FILE:?RESTIC_ENV_FILE is required}
    volumes:
      - restic-cache:/root/.cache/restic
      - /mnt/data/m700/wallos:/repo
      - wallos-data:/data/wallos-data:ro
      - ${EXPORT_DATA}:/data/export
      - ${RESTORE_DATA}:/restore-data

volumes:
  restic-cache:
    name: restic-cache
  wallos-data:
    name: wallos-data
    external: true