name: lldap

volumes:
  lldap-data:
    name: lldap-data

networks:
  m700_default:
    external: true
  lldap_default:
    name: lldap_default

services:
  lldap:
    image: lldap/lldap:stable@sha256:9e605a66c02514bfcffd1b67cafb1e98d50992216bb2871d7ae44622047dd09d
    container_name: lldap
    restart: unless-stopped
    networks:
      - m700_default
      - lldap_default
    expose:
      - "17170"
      - "3890"
    env_file: .env
    volumes:
      - "lldap-data:/data"
    environment:
      UID: 1000
      GID: 1000
      TZ: Europe/Berlin
      LLDAP_VERBOSE: false

      LLDAP_JWT_SECRET_FILE: /run/secrets/jwt
      LLDAP_KEY_SEED_FILE: /run/secrets/key_seed
    secrets:
      - jwt
      - key_seed

secrets:
   jwt:
     file: jwt.txt
   key_seed:
     file: key_seed.txt