name: lldap

volumes:
  lldap-data:
    name: lldap-data

networks:
  m700_default:
    external: true
  lldap_default:
    name: lldap_default

services:

  certbot:
    container_name: certbot
    image: certbot/dns-cloudflare:latest
    command: >-
      certonly
        --non-interactive
        --agree-tos
        --email ${EMAIL}
        --dns-cloudflare 
        --dns-cloudflare-credentials "/run/secrets/cloudflare_token"
        --dns-cloudflare-propagation-seconds 60 
        -d "ldap.optimistic.cloud"
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    secrets:
      - cloudflare_token
    restart: "no"



  lldap:
    image: lldap/lldap:stable@sha256:9e605a66c02514bfcffd1b67cafb1e98d50992216bb2871d7ae44622047dd09d
    container_name: lldap
    restart: unless-stopped
    networks:
      - m700_default
      - lldap_default
    # expose:
    #   - "17170"
    #   - 6360:6360
    ports:
      - "127.0.0.1:17170:17170"
      - "636:6360"
    env_file: .env
    volumes:
      - "lldap-data:/data"
      - ./etc/letsencrypt:/etc/letsencrypt
    environment:
      UID: 1000
      GID: 1000
      TZ: Europe/Berlin
      LLDAP_VERBOSE: false

      LLDAP_JWT_SECRET_FILE: /run/secrets/jwt
      LLDAP_KEY_SEED_FILE: /run/secrets/key_seed

      LLDAP_LDAPS_OPTIONS__ENABLED: true
      LLDAP_LDAPS_OPTIONS__CERT_FILE: /etc/letsencrypt/live/ldap.optimistic.cloud/fullchain.pem
      LLDAP_LDAPS_OPTIONS__KEY_FILE: /etc/letsencrypt/live/ldap.optimistic.cloud/privkey.pem
    secrets:
      - jwt
      - key_seed

secrets:
  jwt:
    file: jwt.txt
  key_seed:
    file: key_seed.txt
  cloudflare_token:
    file: cloudflare.ini