name: lldap-certbot

services:
  certbot:
    container_name: certbot
    image: certbot/dns-cloudflare:latest
    command: >-
      certonly
        --non-interactive
        --agree-tos
        --email ${EMAIL}
        --dns-cloudflare 
        --dns-cloudflare-credentials "/run/secrets/cloudflare_token"
        --dns-cloudflare-propagation-seconds 60 
        -d "ldap.optimistic.cloud"
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    secrets:
      - cloudflare_token

secrets:
   cloudflare_token:
     file: cloudflare.ini