set shell := ["bash", "-eoux", "pipefail", "-c"]

set dotenv-load

help:
  just --list --list-submodules

####################################
######## DOCKER             ########
####################################

[group('docker')]
[doc('Start the stack')]
up:
  docker compose up -d --remove-orphans

[group('docker')]
[doc('Stop the stack')]
down:
  docker compose down --remove-orphans

[group('docker')]
[doc('Restart application stack')]
restart: down && up

[group('docker')]
[doc('Get logs for the application')]
logs:
  docker compose logs -f

[group("docker")]
[doc('List data of the application')]
ls-lldap-data:
  just ls-volume-data lldap-data

[group("docker")]
[doc('List docker volume data')]
[private]
ls-volume-data export_path:
  docker run --rm -v {{export_path}}:/data:ro alpine ls -la /data

[group('certbot')]
[doc('Run certbot to obtain/renew certificates')]
certbot:
  docker compose -f docker-compose.certbot.yaml up -d --remove-orphans