x-healthcheck: &default-healthcheck
  interval: 180s
  timeout: 30s
  retries: 5
  start_period: 60s

services:
  caddy:
    container_name: caddy
    build:
      context: ./conf.d/caddy
      dockerfile: Dockerfile 
    restart: unless-stopped
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/data
      - ./config:/config
      - ./conf.d/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  jellyfin:
    image: jellyfin/jellyfin@sha256:333b647716631443a43c7fabac4b0c46b4e2f036bad19547e00958f10f721b85
    container_name: jellyfin
    expose:
      - 8096/tcp
      - 7359/udp
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAIN}

  beszel:
    image: henrygd/beszel:latest@sha256:3135185161e072a5058f7c05b247345072bd9f3e23a4a9cd8c879880b085bc41
    container_name: beszel
    restart: unless-stopped
    expose:
      - 8090
    volumes:
      - beszel-data:/beszel_data
      - beszel-socket:/beszel_socket
    environment:
      TZ: Europe/Berlin
      USER_CREATION: true
      DISABLE_PASSWORD_AUTH: true
    healthcheck:
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
      <<: *default-healthcheck

  beszel-agent:
    image: henrygd/beszel-agent:latest@sha256:28f42890c6efde336a56c83f976616e41226b5937c79cbb530f5a5ad242ace36
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - beszel-agent-data:/var/lib/beszel-agent
      - beszel-socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 45876
      HUB_URL: http://beszel:8090
      TOKEN: "${BESZEL_TOKEN}"
      KEY: "${BESZEL_KEY}"
    healthcheck:
      test: ['CMD', '/agent', 'health']
      <<: *default-healthcheck

  # Deployment notes
  # SSO auth https://github.com/iv-org/invidious/pull/3164
  invidious:
    image: quay.io/invidious/invidious:latest@sha256:9d972ea5930c2e170b3c4d49bdd9fa09bf03f077d555f58747342062dffc5876
    container_name: invidious
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      TZ: Europe/Berlin
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG_FILE: /config/invidious/config.yml
    volumes:
      - ./conf.d/invidious/config.yml:/config/invidious/config.yml
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      <<: *default-healthcheck
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invidious.rule=Host(`invidious.${DOMAIN}`)"
      - "traefik.http.routers.invidious.entrypoints=https"
      - "traefik.http.routers.invidious.tls.certresolver=letsencrypt"
      - "traefik.http.services.invidious.loadbalancer.server.port=3000"

  companion:
    image: quay.io/invidious/invidious-companion:latest@sha256:5159c1f988555c3b20a4f8041e733d6d75c5acf0be971f991b74141dc44290ea
    container_name: invidious-companion
    environment:
      TZ: Europe/Berlin
    # Use the key generated in the 2nd step
      SERVER_SECRET_KEY: ${INVIDIOUS_SERVER_SECRET_KEY}
    restart: unless-stopped
    # Uncomment only if you have configured "public_url" for Invidious companion
    # Or if you want to use Invidious companion as an API in your program.
    # Remove "127.0.0.1:" if used from an external IP
    #ports:
    #  - "127.0.0.1:8282:8282"
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    cap_drop:
      - ALL
    read_only: true
    # cache for youtube library
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14@sha256:705a5d5b5836f3fcba0d02c4d281e6a7dd9ed2dd4078640f08a1e1e9896e097d
    container_name: invidious-db
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./conf.d/invidious/sql:/config/sql
      - ./conf.d/invidious/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: ${INVIDIOUS_POSTGRES_DB}
      POSTGRES_USER: ${INVIDIOUS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${INVIDIOUS_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      <<: *default-healthcheck

volumes:
  postgresdata:
  companioncache:
  beszel-data:
    name: beszel-data
  beszel-socket:
    name: beszel-socket
  beszel-agent-data:
    name: beszel-agent-data
