services:
  # https://healthchecks.io/docs/self_hosted_docker/
  healthchecks:
    # https://hub.docker.com/r/healthchecks/healthchecks
    image: healthchecks/healthchecks:v4.2@sha256:6b5f593d40994345053f05f86decfa9e17ab1e4422df2ae58abd032a7b14d8f6
    container_name: healthchecks
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - DB=sqlite
      - DB_NAME=/data/hc.sqlite
      - DEBUG=False
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST=${SMTP_HOST}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_PORT=${SMTP_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - SECRET_KEY=${SECRET_KEY}
      - SITE_ROOT=https://hc.${DOMAIN}
      - SITE_LOGO_URL=https://raw.githubusercontent.com/optimistic-cloud/assets/refs/heads/main/logo-light.svg
      - SITE_NAME=Optimistic Cloud
      - REGISTRATION_OPEN=False
      - ADMINS=${ADMINS}

      - MATRIX_ACCESS_TOKEN=${MATRIX_ACCESS_TOKEN}
      - MATRIX_HOMESERVER=${MATRIX_HOMESERVER}
      - MATRIX_USER_ID=${MATRIX_USER_ID}
      - INTEGRATIONS_ALLOW_PRIVATE_IPS=True
    volumes:
      - healthchecks-data:/data
    networks:
      - m700_default

volumes:
  healthchecks-data:

networks:
  m700_default:
    external: true
