x-healthcheck: &default-healthcheck
  interval: 180s
  timeout: 30s
  retries: 5
  start_period: 60s

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest@sha256:03ac4280eec733d004de0a46a3944e8ef0d3fbd9c317027b19492d4ed360aa89
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_NO_ANALYTICS: true
      DOZZLE_REMOTE_AGENT: ${DOZZLE_REMOTE_AGENT}
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      <<: *default-healthcheck