x-healthcheck: &default-healthcheck
  interval: 180s
  timeout: 30s
  retries: 5
  start_period: 60s

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest@sha256:34d7ad621c2c98ff86b5c708f746e44c1363c2aa56a7fd056d5ec44f65ea3335
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_NO_ANALYTICS: true
      DOZZLE_REMOTE_AGENT: ${DOZZLE_REMOTE_AGENT}
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      <<: *default-healthcheck