name: davis

services:
  # Add init container to set permissions
  init:
    image: alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
    volumes:
      - davis-data:/data
    command: |
      sh -c "
        chown -R 82:82 /data && # www-data user and group have the ID 82 in davis image
        chmod -R 700 /data
      "
    restart: "no"

  davis:
    image: ghcr.io/tchapi/davis-standalone:5.4.1@sha256:9db11b957fdce6d56c04185793c149b62db1596035feb876878acef6b3421be4
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    depends_on:
      init:
        condition: service_completed_successfully
    environment:
      - APP_ENV=prod
      - DATABASE_DRIVER=sqlite
      - DATABASE_URL=sqlite:////data/${DATABASE_NAME}
      - MAILER_DSN=smtp://${MAIL_USERNAME}:${MAIL_PASSWORD}@${MAIL_HOST}:${MAIL_PORT}
      - APP_TIMEZONE=Europe/Berlin
      - CALDAV_ENABLED=true
      - CARDDAV_ENABLED=true
      - WEBDAV_ENABLED=false
    volumes:
      - davis-data:/data
    networks:
      - m700_default
      - lldap_default
    expose:
      - "9000"

volumes:
  davis-data:

networks:
  m700_default:
    external: true
  lldap_default:
    external: true