name: davis-backup-restic

x-restic-common: &restic-common
  image: restic/restic:0.18.1@sha256:39d9072fb5651c80d75c7a811612eb60b4c06b32ffe87c2e9f3c7222e1797e76
  hostname: ${HOSTNAME}
  restart: "no"
  stdin_open: true
  user: "0:0"
  environment:
    TZ: Europe/Berlin
    RESTIC_CACHE_DIR: /root/.cache/restic
  env_file:
    - ${RESTIC_ENV_FILE:?RESTIC_ENV_FILE is required}
  volumes:
    - restic-cache:/root/.cache/restic
    - /mnt/data/m700/davis:/repo

services:
  config:
    <<: *restic-common
    command: cat config --json
  check:
    <<: *restic-common
    command: check --read-data-subset "33%" --json
  forget:
    <<: *restic-common
    command: forget --keep-within 365d --quiet
  backup:
    <<: *restic-common
    command: backup /data --tag "git_sha=${GIT_SHA}" --exclude-caches --skip-if-unchanged --json --quiet
    volumes:
      - restic-cache:/root/.cache/restic
      - /mnt/data/m700/davis:/repo
      - davis-data:/data/davis-data:ro
      - ${BACKUP_EXPORT_DATA_DIR}:/data/export

volumes:
  restic-cache:
    name: restic-cache
    external: true
  davis-data:
    external: true