name: davis

services:
  # Add init container to set permissions
  init:
    image: alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
    volumes:
      - davis-data:/data
    command: |
      sh -c "
        chown -R 82:82 /data && # www-data user and group have the ID 82 in davis image
        chmod -R 700 /data
      "
    restart: "no"

  davis:
    image: ghcr.io/tchapi/davis-standalone:5.4.1
    container_name: davis
    restart: unless-stopped
    env_file: .env
    depends_on:
      init:
        condition: service_completed_successfully
    #user: "www-data:www-data"
    environment:
      - APP_ENV=prod
      - DATABASE_DRIVER=sqlite
      - DATABASE_URL=sqlite:////data/davis-database.db # ⚠️ 4 slashes for an absolute path ⚠️ + no quotes (so Symfony can resolve it)
      - MAILER_DSN=smtp://${MAIL_USERNAME}:${MAIL_PASSWORD}@${MAIL_HOST}:${MAIL_PORT}
      - APP_TIMEZONE=Europe/Berlin
      - CALDAV_ENABLED=true
      - CARDDAV_ENABLED=true
      - WEBDAV_ENABLED=false
    volumes:
      - davis-data:/data
    networks:
      - m700_default
    expose:
      - "9000"

volumes:
  davis-data:
    name: davis-data
networks:
  m700_default:
    external: true