set shell := ["bash", "-eoux", "pipefail", "-c"]

set dotenv-load

help:
  just --list --list-submodules

####################################
######## DOCKER             ########
####################################

[group('docker')]
[doc('Start the stack')]
up:
  docker compose up -d --remove-orphans

[group('docker')]
[doc('Stop the stack')]
down:
  docker compose down --remove-orphans

[group('docker')]
[doc('Restart application stack')]
restart: down && up

[group('application')]
[doc('Migrate database')]
migrate:
  docker exec -it davis sh -c "APP_ENV=prod bin/console doctrine:migrations:migrate --no-interaction"

[group('docker')]
[doc('Get logs for the application')]
logs:
  docker compose logs -f

[group('docker')]
[doc('Get logs for the application')]
davis-log-tail:
    docker exec -it davis tail /var/www/davis/var/log/prod.log

[group("docker")]
[doc('List data of the application')]
ls-davis-data:
  just ls-volume-data davis-data

[group("docker")]
[doc('List docker volume data')]
[private]
ls-volume-data export_path:
  docker run --rm -v {{export_path}}:/data:ro alpine ls -la /data

####################################
######## BACKUP             ########
####################################

[group("backup")]
prepare-backup-data:
  bash prepare_backup_data.sh

[group("backup")]
cleanup-backup-data:
  #!/usr/bin/env bash
  set -eoux pipefail

  export_path="${EXPORT_DATA:?EXPORT_DATA is required}"

  rm -rf "${export_path}"

[group("backup")]
backup +backup_targets: && cleanup-backup-data up
  bash backup.sh {{backup_targets}}

[group("backup")]
restore backup_target snapshot_id="latest":
  #!/usr/bin/env bash
  mkdir -p "${RESTORE_DATA}"
  just restic-restore {{backup_target}} {{snapshot_id}}

####################################
######## RESTIC             ########
####################################

[group('restic')]
[doc('Init repository')]
restic-init backup_target:
  just _restic-run {{backup_target}} init

[group('restic')]
[doc('Restore data')]
[private]
restic-restore backup_target snapshot_id:
  just _restic-run {{backup_target}} restore {{snapshot_id}} --target /restore-data

[group('restic')]
[doc('Get snapshots')]
restic-snapshots backup_target count="5":
  just _restic-run {{backup_target}} --quiet snapshots --latest {{count}}

[group('restic')]
[doc('List files in the latest snapshot')]
restic-ls backup_target snapshot_id="latest":
  just _restic-run {{backup_target}} --quiet ls {{snapshot_id}}

[group('restic')]
[doc('Get stats of the repository')]
restic-stats backup_target:
  just _restic-run {{backup_target}} stats --mode raw-data

[group('restic')]
[doc('Unlock repository')]
restic-unlock backup_target:
  just _restic-run {{backup_target}} --quiet unlock

[group('restic')]
[doc('Prune snapshots')]
restic-prune backup_target:
  just _restic-run {{backup_target}} --quiet prune

[group('restic')]
[private]
[doc('For each restic command but not backup, as it needs additional volumes and environment variables')]
_restic-run backup_target +restic_args:
  #!/usr/bin/env nu

  let backup_target = "{{backup_target}}"

  with-env { 
    HOSTNAME: "m700"
    RESTIC_ENV_FILE: $"($backup_target).restic.env" 
  } {
    ^docker compose -f docker-compose.backup.yaml run --rm restic {{restic_args}}
  }

[group('utils')]
[private]
[doc('Removes temporary files created during backup')]
_cleanup:
  rm -rf "${EXPORT_DATA}"
  rm -rf "${RESTORE_DATA}"