set shell := ["bash", "-eoux", "pipefail", "-c"]

set dotenv-load

help:
  just --list --list-submodules

####################################
######## DOCKER             ########
####################################

[group('docker')]
[doc('Start the stack')]
up:
  docker compose up -d --remove-orphans

[group('docker')]
[doc('Stop the stack')]
down:
  docker compose down --remove-orphans

[group('docker')]
[doc('Restart application stack')]
restart: down && up

[group('docker')]
[doc('Get logs for the application')]
logs:
  docker compose logs -f

[group("docker")]
[doc('List data of the application')]
ls-davis-data:
  just ls-volume-data davis-data

[group("docker")]
[doc('List docker volume data')]
[private]
ls-volume-data export_path:
  docker run --rm -v {{export_path}}:/data:ro alpine ls -la /data

[group('application')]
[doc('Migrate database')]
migrate:
  docker exec -it davis sh -c "APP_ENV=prod bin/console doctrine:migrations:migrate --no-interaction"

[group('application')]
[doc('Get logs for the application')]
davis-log-tail:
    docker exec -it davis tail /var/www/davis/var/log/prod.log

####################################
######## BACKUP             ########
####################################

[group("backup")]
prepare-backup-data:
  bash prepare_backup_data.sh

[group("backup")]
cleanup-backup-data:
  #!/usr/bin/env bash
  set -eoux pipefail

  backup_export_data_dir="${BACKUP_EXPORT_DATA_DIR:?BACKUP_EXPORT_DATA_DIR is required}"

  rm -rf "${backup_export_data_dir}"

[group("backup")]
backup +backup_targets: && cleanup-backup-data up
  bash backup.sh {{backup_targets}}

[group("backup")]
restore backup_target snapshot_id="latest":
  #!/usr/bin/env bash
  restore_data_dir="${BACKUP_RESTORE_DATA_DIR:?BACKUP_RESTORE_DATA_DIR is required}"
  mkdir -p "${restore_data_dir}"
  just restic-restore {{backup_target}} {{snapshot_id}}