name: outline

services:
  # https://www.getoutline.com/
  outline:
    container_name: outline
    # https://hub.docker.com/r/outlinewiki/outline/tags
    # https://github.com/outline/outline/releases
    image: outlinewiki/outline:1.7.1@sha256:361df7040e6f0d7abac768b99f40122197921626a7e69501aabb5fcb496fc1b4
    env_file: .env
    restart: unless-stopped
    expose:
      - "3001"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    networks:
      - m700_default
      - outline

  redis:
    image: redis@sha256:315270d166080f537bbdf1b489b603aaaa213cb55a544acfa51feb7481abb1c0
    env_file: .env
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - outline

  postgres:
    container_name: outline-postgres
    image: postgres:18@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
    env_file: .env
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - database-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - outline

volumes:
  storage-data:
  database-data:

networks:
  m700_default:
    external: true
  outline:
    name: outline
