name: outline

services:
  # https://www.getoutline.com/
  outline:
    container_name: outline
    # https://hub.docker.com/r/outlinewiki/outline/tags
    # https://github.com/outline/outline/releases
    image: outlinewiki/outline:1.7.0@sha256:b13ccd15653513a79eb66283bfa91287f5e3d0944d8cb056d5288b8565992de5
    env_file: .env
    restart: unless-stopped
    expose:
      - "3001"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    networks:
      - m700_default
      - outline

  redis:
    image: redis@sha256:315270d166080f537bbdf1b489b603aaaa213cb55a544acfa51feb7481abb1c0
    env_file: .env
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - outline

  postgres:
    container_name: outline-postgres
    image: postgres:18@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a
    env_file: .env
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - database-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - outline

volumes:
  storage-data:
  database-data:

networks:
  m700_default:
    external: true
  outline:
    name: outline
